-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggRDZkVJaojL+17pa
8G2Mk53SoCOI6BxZK1eoAis4XoqgCgYIKoZIzj0DAQehRANCAASVwaTATAigF2yZ
RFXNSxTlC1WAM61CmmII5kZgHRq6cvEoIkYwNyOUubf2AjBTUFORy4ayuboNrxd0
cT53RySV
-----END PRIVATE KEY-----